# Introduction

**numpy**

In [3]:
#numpy - numerical python
#package for computation and processing of multidimensional & single dimensional arrays
#Travis Oliphant in 2005- features of ancestor module Numeric into another module Numarray
#implementing multidimensional arrays & matrices - data strucutres

#easier syntax -1st choice for data scientist
#convenient & efficient to handle vast data
#fast

**advantages**

In [4]:
#1.array oriented
#2.efficient multi dimentional arrays
#3.scientific computations
#4.Fourier tarnsform,reshaping
#5.built in functions for linear algebra,random num generation


#repalcement to MATLAB ,python with matplotlib and scipy

# Ndarray

In [5]:
#n dimensional array- collection of similar type of elements
import numpy as np
a = np.array
print(a)
print(type(a))

<built-in function array>
<class 'builtin_function_or_method'>


In [6]:
#can pass collection object into the array routine to create equivalent nd array
#np.array(object,dtype=None,copy=True,order=None,subok=False,ndmin=0)
#order - C(column order),R(row order) or A(any)
#ndmin- mininum directions

a = np.array([1,2,3,4,5,6])
print(a)
print(a.ndim)
#itemsize -size of each item in bytes
print(a.itemsize)
print(a.dtype)
print(a.size)
print(a.shape)

[1 2 3 4 5 6]
1
8
int64
6
(6,)


**reshape**

In [7]:
a = np.array([[[1,2],[3,4],[5,6]]])
print(a)
a=a.reshape(2,3)
print(a)

[[[1 2]
  [3 4]
  [5 6]]]
[[1 2 3]
 [4 5 6]]


**slicing**

In [8]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[0,1])
print(a[2,0])

2
5


**linspace**

In [40]:
#even spaces between interval
a = np.linspace(5,15,10)
print(a)

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


**min,max,sum**

In [10]:
a = np.array([1,3,65,2,34,44])
print(a.max())
print(a.min())
print(a.sum())

65
1
149


**Axis 1 row,0 col**

In [11]:
a = np.array([[1,5,3],[4,2,6]])
print("max in col",a.max(axis=0))
print("min in row",a.min(axis=1))
print("sum of all rows",a.sum(axis = 1))

max in col [4 5 6]
min in row [1 2]
sum of all rows [ 9 12]


**square root &  standard deviation**

In [12]:
a = np.array([[1,5,3],[4,2,6]])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.23606798 1.73205081]
 [2.         1.41421356 2.44948974]]
1.707825127659933


**arithmetic operations**

In [13]:
a = np.array([[1,5,3],[4,2,6]])
b = np.array([[2,6,3],[6,4,4]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 3 11  6]
 [10  6 10]]
[[-1 -1  0]
 [-2 -2  2]]
[[ 2 30  9]
 [24  8 24]]
[[0.5        0.83333333 1.        ]
 [0.66666667 0.5        1.5       ]]


**array concatenation**

In [14]:
#vertical stacking and horizontal stacking
a = np.array([[1,5,3],[4,2,6]])
b = np.array([[2,6,3],[6,4,4]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 5 3]
 [4 2 6]
 [2 6 3]
 [6 4 4]]
[[1 5 3 2 6 3]
 [4 2 6 6 4 4]]


**dtype**

In [15]:
#syn:np.dtype(object,align,copy)
#align-boolean if true adds aextra padding to equal C struct
#copy - creates copy of dtype object
d=np.dtype(np.int32)
print(d)
d=np.int32(4)
print(d)

int32
4


## Numpy Array Creation

**numpy.empty**

In [18]:
#uninitialized array of specified shape and data type
#syn:numpy.empty(shape,dtype=float,order='C')
#c-style row-major order -default
#F for FORTRAN-style column-major order
a=np.empty((3,2),dtype=int)
print(a)

[[1 5]
 [3 4]
 [2 6]]


**numpy.zeros**

In [20]:
#each item 0
#syn:numpy.zeros(shape, dtype = float, order = 'C')  
a=np.zeros((3,2),dtype=int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


**numpy.ones**

In [22]:
#each item 1
#syn:numpy.ones(shape, dtype = float, order = 'C')  
a=np.ones((3,2),dtype=int)
print(a)

[[1 1]
 [1 1]
 [1 1]]


# Numpy array from existing

**numpy.asarray**

In [25]:
#uses tuples or lists
#syn: numpy.asarray(sequence,dtype=None,order=None)
#list
a = [1,2,3,4,5,6]
x=np.asarray(a)
print(type(x))
print(a)

<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]


In [26]:
#tuple
a = (1,2,3,4,5,6)
x=np.asarray(a)
print(type(x))
print(a)

<class 'numpy.ndarray'>
(1, 2, 3, 4, 5, 6)


In [35]:
#2lists
l = [[1,2,3,3,5],[3,4,5,6,7]] 
a = np.asarray(l)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[1 2 3 3 5]
 [3 4 5 6 7]]


In [29]:
l = [[1,2,3],[3,4,5,6,7]] #same size should be there
a = np.asarray(l)
print(type(a))
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**numpy.frombuffer**

In [33]:
#specified buffer
#syn:numpy.frombuffer(buffer,dtype=float,count=-1,offset=0)
#buffer-buffer interface
#offset-starting position
l=b"wwryrecvg"
print(type(l))
a=np.frombuffer(l,dtype="S1") #s1,s2 are string datatypes
print(a)
print(type(a))

<class 'bytes'>
[b'w' b'w' b'r' b'y' b'r' b'e' b'c' b'v' b'g']
<class 'numpy.ndarray'>


**numpy.fromiter**

In [34]:
#iterable object-1d array
#syn:numpy.fromiter(iterable,dtype,count=-1)
l=[1,2,3,4,5]
i = iter(l)
a=np.fromiter(i,dtype=float)
print(a)
print(type(a))

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


## Numpy array with numerical range

**numpy.arange**

In [37]:
#even spaced between interval
#syn:numpy.arrange(start,stop,step,dtype)
#start initial 0
a=np.arange(0,12,2,float)
print(a)

[ 0.  2.  4.  6.  8. 10.]


**numpy.linspace**

In [39]:
#not allows us step
#syn:numpy.linspace(start,stop,num,endpoint,retstep,dtype)
#num-count od evenly scpaced ,default 50
#retstep-boolean value,represents steps & sample between consecutive numbres
a=np.linspace(10,20,10,endpoint=False)
print(a)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


**numpy.logspace**

In [41]:
#evenly seperated on logscale
#syn:numpy.logspace(start,stop,num,endpoint,base,dtype)
#base-base of logspace
a=np.logspace(10,20,num=5,endpoint=True)
print(a)

[1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


# Numpy Boardcasting

In [42]:
#as 2 different shape arrays cant perform multiplication
#in board casting smaller array is boardcast ot larger array

#cases
#1.smaller dimension array appended with 1 its shape
#2.size of output be max of input
#3.input can be used in calculation if its size in particular dimension match o/p size or exactly 1
#4.if input size is 1,then 1st data entry used for calculation 


#rules
#1.input have same shape
#2.same no.of dimensions,length of each dimension same or 1
#3.array with fewer dimension can be appended with 1 in its shape
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8]) 
print(a+b)

[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


# Numpy Array Iteration

In [3]:
import numpy as np
#nditer -standard Iterator interface
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
for x in np.nditer(a):
    print(x,end="  ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1  2  3  4  5  6  7  8  9  10  11  12  

**Transpose**

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b=a.T
print(b)
for x in np.nditer(b):
    print(x,end="  ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
1  2  3  4  5  6  7  8  9  10  11  12  

**Order of iteration**

In [8]:
#c 
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("c order")
c=a.copy(order="C")
print(c)
for x in np.nditer(c):
    print(x,end="  ")
#f 
print("\nf order")
f=a.copy(order="F")
print(f)
for x in np.nditer(f):
    print(x,end="  ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
c order
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1  2  3  4  5  6  7  8  9  10  11  12  
f order
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1  5  9  2  6  10  3  7  11  4  8  12  

**Array value rewrite**

In [9]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=2*x
    print(x,end="  ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2  4  6  8  10  12  14  16  18  20  22  24  

## Numpy Bitwise

In [12]:
a=10
b=12
print(bin(a))
print(bin(b))
print(np.bitwise_and(a,b),bin(np.bitwise_and(a,b)))
print(np.bitwise_or(a,b),bin(np.bitwise_or(a,b)))
#invert - not operand,2's compliment-if signed
print(np.invert(a))
print("20",np.left_shift(20,3))
print("20",np.right_shift(20,3))
print("20 in 8 bits",np.binary_repr(20,8))

0b1010
0b1100
8 0b1000
14 0b1110
-11
20 160
20 2
20 in 8 bits 00010100


# String functions

In [15]:
print("1.",np.char.add(["welcome","hi"],["hello","hell"]))
print("2.",np.char.multiply("hell",3))
print("3.",np.char.center("sneha",20,"*"))
print("4.",np.char.capitalize("sneha suresh"))
print("5.",np.char.title("sneha suresh"))
print("6.",np.char.lower("SNEHA SURESH"))
print("7.",np.char.upper("sneha suresh"))
print("8.",np.char.split("sneha suresh madhu"),sep=" ")
print("9.",np.char.splitlines("sneha\nsuresh\nmadhu"))
print("10",np.char.join(':','HM')) 
e=np.char.encode("sneha suresh","cp500")
d=np.char.decode(e,"cp500")
print(e)
print(d)

1. ['welcomehello' 'hihell']
2. hellhellhell
3. *******sneha********
4. Sneha suresh
5. Sneha Suresh
6. sneha suresh
7. SNEHA SURESH
8. ['sneha', 'suresh', 'madhu']
9. ['sneha', 'suresh', 'madhu']
10 H:M
np.bytes_(b'\xa2\x95\x85\x88\x81@\xa2\xa4\x99\x85\xa2\x88')
sneha suresh


# Numpy Mathematical functions

**Trigonometric functions**

In [18]:
a = np.array([0, 30, 60, 90, 120, 150, 180]) 
print(np.sin(a * np.pi/180),"\n")
print(np.cos(a * np.pi/180),"\n")
print(np.tan(a * np.pi/180))

[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16] 

[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00] 

[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [20]:
#round
a=np.array([12.202, 90.23120, 123.020, 23.202])  
print(a)
print(np.around(a,2))
print(np.around(a,-1))
print(np.floor(a)) 
print(np.ceil(a)) 

[ 12.202   90.2312 123.02    23.202 ]
[ 12.2   90.23 123.02  23.2 ]
[ 10.  90. 120.  20.]
[ 12.  90. 123.  23.]
[ 13.  91. 124.  24.]


# Numpy Statistical functions

In [21]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
print(a)
print("element array",np.amin(a))
print("element array",np.amax(a))
print("element rows array",np.amin(a,0))
print("element rows array",np.amax(a,0))
print("element cols array",np.amin(a,1))
print("element cols array",np.amax(a,1))

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]
element array 2
element array 80
element rows array [ 2 10 10]
element rows array [80 43 31]
element cols array [ 2 31 10]
element cols array [20 80 43]


In [22]:
#ptp =peak to peak ,range of axis
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
print(a)
print("along 1",np.ptp(a,1))
print("along 0",np.ptp(a,0))

#np.percentile(input,q,axis)
#q-(1-100)
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
print(a)
print("along 1",np.percentile(a,10,1))
print("along 0",np.percentile(a,10,0))

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]
along 1 [18 49 33]
along 0 [78 33 21]
[[ 2 10 20]
 [80 43 31]
 [22 43 10]]
along 1 [ 3.6 33.4 12.4]
along 0 [ 6.  16.6 12. ]


**median,mean,avg**

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print(a)
print(np.median(a,0))
print(np.mean(a,0))
print(np.average(a,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[4. 5. 6.]
[2. 5. 8.]


## Sorting & searching

In [27]:
#np.sort(a,axis,kind,order)  
#kind-default quick
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
print("col",np.sort(a))
print("row",np.sort(a,0))

b=np.dtype([('name','S10'),('marks',int)]) 
c=np.array([('Mukesh',200),('John',251)],dtype=b)
print(np.sort(c,order="name"))

col [[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
row [[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
[(b'John', 251) (b'Mukesh', 200)]


**argsort**

In [29]:
#indices sort
a=np.array([90, 29, 89, 12])
b=np.argsort(a)
print(b)
for i in b:
    print(a[i],end=" ")

[3 1 2 0]
12 29 89 90 

**lexsort**

In [31]:
#sort array using sequence of keys
a=np.array(['a','b','c','d','e'])
b=np.array([12,90,232,23,42])
c=np.lexsort((a,b))
print(c)
for i in c:
    print(a[i],b[i])

[0 3 4 1 2]
a 12
d 23
e 42
b 90
c 232


**where**

In [32]:
a=np.array([12,90,38,12,21])
print(np.where(a>20))

(array([1, 2, 4]),)


In [7]:
#numpy array to another array doesn't make the direct copy of original array
import numpy as np
a=np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])
print(a)
print("id a:",id(a))
b=a
print(b)
print("id b:",id(b))
b.shape=4,3
print(b)
print("reflects")
print(a)

[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
id a: 139967287525168
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
id b: 139967287525168
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]
reflects
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]


**.view**

In [8]:
a=np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])
print(a)
print("id a:",id(a))
b=a.view()
print(b)
print("id b:",id(b))
b.shape=4,3
print(b)
print("not reflects")
print(a)

[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
id a: 139967287788432
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
id b: 139967287788336
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]
not reflects
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]


**.copy**

In [9]:
a=np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]])
print(a)
print("id a:",id(a))
b=a.copy()
print(b)
print("id b:",id(b))
b.shape=4,3
print(b)
print("not reflects")
print(a)

[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
id a: 139967287525264
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
id b: 139967287788912
[[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]
not reflects
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]


## Numpy matrix library

**numpy.matlib.empty**

In [1]:
#new matrix with uninitialised entries
#syn:np.matlib.empty(shape,dtype,order)
import numpy as np
import numpy.matlib
print(numpy.matlib.empty((3,3)))

[[ 6.95065524e-310  6.95065524e-310 -7.89651271e+030]
 [ 6.95063736e-310  6.95063737e-310  2.42092166e-322]
 [ 6.95065524e-310  4.67320321e-310 -2.31585072e+023]]


**numpy.matlib.zeros**

In [3]:
#initialised with zeros
print(numpy.matlib.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**numpy.matlib.ones**

In [5]:
#initialised with ones
print(numpy.matlib.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**numpy.matlib.eye**

In [6]:
#diagonal elements initialized to 1 and zero elsewhere
#syn:numpy.matlib.eye(n,m,k,dtype) 
#n-rows,m-cols default n,k-index of diagonal
print(numpy.matlib.eye(n=3,M=3,k=0,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**numpy.matlib.identity**

In [7]:
#identity matrix of the given size
print(numpy.matlib.identity(5,dtype=int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


**numpy.matlib.rand**

In [8]:
#random values
print(numpy.matlib.rand(3,3))

[[0.18333692 0.24405499 0.75869768]
 [0.07995798 0.62367916 0.68569695]
 [0.43692983 0.50786998 0.14672834]]


## Numpy Linear Algebra

**np.dot**

In [13]:
#dot product of the two matrice
import numpy as np  
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)
print("calculation:[100 * 10 + 200 * 12, 100 * 20 + 200 * 21] [23*10+12*12, 23*20 + 12*21]")

[[3400 6200]
 [ 374  712]]
calculation:[100 * 10 + 200 * 12, 100 * 20 + 200 * 21] [23*10+12*12, 23*20 + 12*21]


**np.vdot**

In [14]:
# dot product of two vectors
import numpy as np  
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)
print("calc:100 *10 + 200 * 20 + 23 * 12 + 12 * 21 = 5528 ")

5528
calc:100 *10 + 200 * 20 + 23 * 12 + 12 * 21 = 5528 


**np.inner**

In [15]:
#sum of the product of inner elements of the one-dimensional array
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)

130


**np.matmul**

In [16]:
#multiplication of the two matrices,error if shape of matrix not aligned
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul) 

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


**numpy determinant**

In [18]:
#if [[a,b],[c,d]],det is ad-bc
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


**numpy.linalg.inv**

In [19]:
#inverse of matrix
a=np.array([[1,2],[3,4]])  
print(a)
b=np.linalg.inv(a)
print(b)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Matrix multiplication

In [20]:
#matrix multiplication using NumPy-Vectorization
#remove or reduce the for loops-faster computation
#3 methods

**1.multiply**

In [21]:
#1.multiply() - element wise multiplication of matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
b=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
c=np.multiply(a,b)  
print(a)
print(b)
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
[[[ 9 16 21]
  [24 25 24]
  [21 16  9]]]


**2.matmul**

In [22]:
#2.matmul() - matrix product of 2 arrays
a=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
b=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
c=np.matmul(a,b)  
print(a)
print(b)
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
[[[ 30  24  18]
  [ 84  69  54]
  [138 114  90]]]


**3.dot**

In [23]:
#3.dot() - dot product of 2 arrays
a=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
b=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
c=np.dot(a,b)  
print(a)
print(b)
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[9 8 7]
  [6 5 4]
  [3 2 1]]]
[[[[ 30  24  18]]

  [[ 84  69  54]]

  [[138 114  90]]]]


## np.concatenate

In [24]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y))  
z 

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [25]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=0)  
z  

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [26]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y.T), axis=1)  
print(z) 

[[ 1  2 12]
 [ 3  4 30]]


In [27]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=None)  
z  

array([ 1,  2,  3,  4, 12, 30])

## np.append

In [28]:
#syn:numpy.append(arr, values, axis=None) 
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
c

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

## np.reshape

In [33]:
#syn:numpy.reshape(arr, new_shape, order='C')  
x=np.arange(12)  
y=np.reshape(x, (4,3))  
print(x)  
y  

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
x=np.arange(12)  
y=np.reshape(x, (4, 3), order='F')  
print(x)  
y

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## np.transpose

In [34]:
#syn:numpy.transpose(arr, axis=None)  
a= np.arange(6).reshape((2,3))  
a  
b=np.transpose(a)  
b 

array([[0, 3],
       [1, 4],
       [2, 5]])

# Load.txt

In [ ]:
a=numpy.loadtxt("fname.txt", dtype=float, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)  

## ndarray.flatten

In [42]:
#syn:ndarray.flatten(order='C')  
import numpy as np
a = np.array([[1,4,7], [2,5,8],[3,6,9]])  
b=a.flatten()  
b  

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [45]:
a = np.array([[1,4,7], [2,5,8],[3,6,9]])  
b=a.flatten('C')  
print(b) 

[1 4 7 2 5 8 3 6 9]


In [46]:
 a = np.array([[1,4,7], [2,5,8],[3,6,9]])  
b=a.flatten('F')  
print(b) 

[1 2 3 4 5 6 7 8 9]


In [47]:
a = np.array([[1,4,7], [2,5,8],[3,6,9]])  
b=a.flatten('K')  
b 

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

## np.ravel

In [48]:
#2d or multi d to 1d
#syn:numpy.ravel(x, order='C') 
x = np.array([[1, 3, 5], [11, 35, 56]])  
y = np.ravel(x, order='F')  
z = np.ravel(x, order='C')  
p = np.ravel(x, order='A')  
q = np.ravel(x, order='K') 
print(y)
print(z)
print(p)
print(q)

[ 1 11  3 35  5 56]
[ 1  3  5 11 35 56]
[ 1  3  5 11 35 56]
[ 1  3  5 11 35 56]
